name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    steps:
      - name: Change secrets.txt to secrets.dart
        run: |
          cp bin/impaktfull_mailer_secrets.txt bin/impaktfull_mailer_secrets.dart
      - name: Publish to pub.dev
        permissions:
          id-token: write # Required for authentication using OIDC
        uses: Impaktfull/gh_action_dart_conventional_release/.github/workflows/flutter_release.yml@main
        with:
          environment: "pub.dev"
